version: '3.0'  

services:
  partya: 
    image: corda/corda-zulu-java1.8-4.8:latest
    container_name: partyA
    ports:
      - "10006:10201"
      - "2001:2222"
    volumes:
      - ./node/node.conf:/etc/corda/node.conf
      - ./node/certificates:/opt/corda/certificates
      - ./node/persistence:/opt/corda/persistence
      - ./node/logs:/opt/corda/logs
      - ./node/cordapps:/opt/corda/cordapps
      - ./node/node-infos:/opt/corda/additional-node-infos
      - ./node/network-parameters:/opt/corda/network-parameters