services:
  buyer-api:
    image: amitter1/xarda-api
    container_name: buyer-api
    ports:
      - "8080:8080"
    environment:
      - config.rpc.host=host.docker.internal
      - config.rpc.port=10006
      - config.rpc.username=user1
      - config.rpc.password=test

  supplier-api:
    image: amitter1/xarda-api
    container_name: supplier-api
    ports:
      - "8081:8080"
    environment:
      - config.rpc.host=host.docker.internal
      - config.rpc.port=10009
      - config.rpc.username=user1
      - config.rpc.password=test

  lcl-company-api:
    image: amitter1/xarda-api
    container_name: lcl-company-api
    ports:
      - "8082:8080"
    environment:
      - config.rpc.host=host.docker.internal
      - config.rpc.port=10012
      - config.rpc.username=user1
      - config.rpc.password=test

  shipping-line-api:
    image: amitter1/xarda-api
    container_name: shipping-line-api
    ports:
      - "8083:8080"
    environment:
      - config.rpc.host=host.docker.internal
      - config.rpc.port=10015
      - config.rpc.username=user1
      - config.rpc.password=test


